### ISSUE TITLE
Bottom most row missed

### ISSUE THREAD

**Issue by cj1985** [tabulapdf/tabula#1029]
In this file, [Entities.pdf](https://github.com/tabulapdf/tabula/files/3338644/Entities.pdf), it seems that Tabula misses the bottom row of every page (except p. 42).

(May I suggest that Tabula come with a warning that there may be many errors. I operated on the assumption that Tabula had mostly extracted the table correctly, but then I repeatedly discover errors and so have to repeatedly start my work all over again. This has wasted me many hours. This here is just the latest error I've discovered.)

**Comment by jazzido** [comment]
Thanks for your report, @cj1985. Tabula is a tool for assisting in the extraction of tables from a format which is unsuitable for the exchange of structured information. As such, we don't make any promise about the quality of the output that it produces.

I would say that I'm sorry that you "wasted many hours" because of that. But, hey, at least you didn't waste any _money_: in fact, _WE_ did, as the unpaid, volunteer maintainers of this tool.

We will look into this issue, as time permits. In the interim, may I suggest that you look into commercial alternatives.

Cheers.
