### ISSUE TITLE
PDF tables are not images but Tabula converting them into gibberish

### ISSUE THREAD

**Issue by SabahatPK** [tabulapdf/tabula#1056]
What error message did you get? 
No error message; just funky text after converting. I converted several PDFs from the same source and they all converted fine, so I know they are all text and not pictures. It would be strange if they switched over to pictures after years of text-based tables.

What steps did you take? Tried "Stream" and "Lattice" to no avail.
(https://github.com/tabulapdf/tabula/files/3691230/BranchlessBanking-Oct-Dec-2018.pdf)

What PDF were you trying to extract data from? 
[BranchlessBanking-Oct-Dec-2018.pdf](https://github.com/tabulapdf/tabula/files/3691253/BranchlessBanking-Oct-Dec-2018.pdf)
 Or you can go directly to source: http://www.sbp.org.pk/publications/acd/2018/BranchlessBanking-Oct-Dec-2018.pdf

What version of Tabula are you using? 1.2.1

What platform are you on? Windows 10 Pro

**Comment by jazzido** [comment]
Thanks for your report.

It's likely that your PDF has bad glyph-to-character mappings. Try copying from Acrobat Reader or other PDF viewing app and pasting onto a text editor. Do you also see gibberish instead of the actual text? If so, and unless you're willing to do some serious, low-level PDF debugging, OCR is your only option.

See this Stack Overflow answer for more information: http://stackoverflow.com/questions/12184304/if-pdf-copypaste-gives-garbage-text-what-is-wrong-with-the-pdf-source-code
