### ISSUE TITLE
Diacritic characters

### ISSUE THREAD

**Issue by prayner96** [tabulapdf/tabula#1074]
Hiya,

My issue is that the diacritic characters are not being converted properly. When tabula extracts data from the .pdf, the extraction works beautifully. However, upon conversion into a .csv document, the diacritic characters are not translated and are instead replace with mismatching symbols. 

I understand that this is an issue your team has faced before but I could not find a solution embedded within the GitHub issues or on the website. Please let me know if there is a worked solution to this problem.

Cheers,
Paul-Eric

**Comment by jeremybmerrill** [comment]
Hiya Paul-Eric,

The problem is likely with Microsoft Excel, opening the CSV file with the
wrong "encoding". If you check in our Github issues or just Google around
with these terms, you should be able to find instructions on how to open a
CSV in your version of Excel using the UTF-8 encoding -- which should make
Excel display the diacritics correctly.

Jeremy B. Merrill

**Comment by prayner96** [comment]
Fantastic, I was using the CSV in R but all I had to do was specify:
read.csv("tabula_file.csv", **encoding = "UTF-8"**)

Thanks for the prompt reply Jeremy.
