### ISSUE TITLE
enable uploading multiple pdfs

### ISSUE THREAD

**Issue by jeremybmerrill** [tabulapdf/tabula#244]
re: #196

@floodfish: What do you think happens after you upload multiple PDFs? You stay on the upload page, and the new PDFs get added to the file library? (and maybe highlighted?) 

Right now, when your single file is done uploading, it takes you direclty to hte selection page.

**Comment by floodfish** [comment]
@jeremybmerrill Yes, you stay on the upload page, and the new PDFs get added to the file library. I'd suggest doing that even for a single file upload.

The new file(s) should probably go to the top of the list, but I guess I'm not sure how that works if you've sorted the list by another attribute.

Some kind of highlighting is a good idea ... could either be a flash-and-fade or more permanent. Either way, CSS can handle it as long as there is a class on the newly added files.

**Comment by jeremybmerrill** [comment]
Gotcha. But do you think we should keep the current behavior where if you upload only one file, you get taken directly to the selection page?

**Comment by jazzido** [comment]
Yes. In fact, I don't think that being able to upload multiple PDFs is a crucial feature. Users interact with Tabula by impulse: find a PDF, upload, select, get the data, close it. We shouldn't add an extra step to that.

**Comment by floodfish** [comment]
I guess I disagree with Manuel on this. It should be up to the user to control when they navigate to another state of the app. I think that's more in line with expected behavior of file managers in general. To do otherwise is disorienting to non-powerusers. And I can imagine plenty of scenarios where someone would import a file and still want to view the import page and file list.

But maybe it can be a checkbox option or a second button? Something like "upload and stay here" vs "upload and extract"?

Or we could try it out and get some user feedback.

**Comment by jazzido** [comment]
> I guess I disagree with Manuel on this. It should be up to the user to control when they navigate to another state of the app. I think that's more in line with expected behavior of file managers in general. To do otherwise is disorienting to non-powerusers. And I can imagine plenty of scenarios where someone would import a file and still want to view the import page and file list. 

Imagine that you have a set of images and you want to crop them, and that the crop area is different for each one of them. Would you think it’s natural to first move those images to a “staging area” of sorts, and then clicking on each one of them to select the area that you want to crop? That’s analogous to uploading a bunch of PDFs *and then* clicking on each one of them for processing.


> But maybe it can be a checkbox option or a second button? Something like "upload and stay here" vs "upload and extract”? 


Either way, let’s not introduce more complexity.

OTOH, is it possible to upload in parallel from the browser? (I don’t know. I’ve never implemented such a thing). If not, what’s the benefit of blocking until *n* uploads have finished before I can use the tool?
If it’s indeed possible, then we have a problem because we have a single progress bar. We would need to move the progress bar inside each row of the uploaded files list or something like that.

**Comment by jazzido** [comment]
Actually, moving the progress bar inside each item of the uploaded files list might be a good idea

  1. user clicks 'upload'
  2. new item appears at the top of the list, with a smaller progress bar next to the file name
  3. when the upload is ready, make the 'extract data' button appear.

**Comment by jeremybmerrill** [comment]
new PDF flashes when it's done: 8c04f52

we've got to figure out whether or not, when a single PDF is uploaded, whether you get taken directly to the extraction page, or if we depend on the flash to guide the user to click the "extract data" button

**Comment by jeremybmerrill** [comment]
Since this requires re-engineering a lot of the progress bar infrastructure, I think maybe it's worth holding off, saving this enhancement for later?

You can't upload in parallel, but "uploading" isn't the bottleneck, it's all the serverside processing, which can happen in parallel. HTML5 multiple file field elements work fine: we just have to append `[]` to the file element, e.g. `name='files[]'` and it'll work great out of the box. But then we need to loop over that in the `upload.json` method and then figure out how to make the progress bar stuff work for multiple uploads.

**Comment by floodfish** [comment]
From a UI perspective, I like the idea of inline progress bars. The user doesn't need to know if it's "uploading" or "processing" ... they just need to know if their file is ready.

**Comment by floodfish** [comment]
To earlier discussion re. going directly to the extraction page, assuming this is not already resolved:

I still prefer staying on the staging page. As a user I like to determine when I'm ready for the next stage of a process, and find it disorienting—if not disruptive—otherwise (I'd say the same for the hypothetical image processing app). But without polling users or A/B testing, I can't say this is definitely the best way for Tabula!

I agree that adding additional complexity/preferences is not ideal. 

Does Jeremy or Mike have a preference? Is polling or testing users worth considering?

**Comment by jeremybmerrill** [comment]
I think there's a decent reason to tell users what's happening in processing: often folks complain about how long Tabula takes, so it's useful to tell them what the hell is happening. I assume that allays some of their complaints. Not important enough to dictate the design of the library page, but worht keeping in mind, I htink.

My instinct is that we should take users directly to the extraction page. Since we're presumably going to release this redesign as a beta, we could just ask the preview users. (Maybe we should ask for their email so we can send them a survey?)

**Comment by floodfish** [comment]
It would be great to get e-mail addresses for anyone using the beta release.

> I think there's a decent reason to tell users what's happening in processing: often folks complain about how long Tabula takes, so it's useful to tell them what the hell is happening.


Sure, it's fine to display a changing description alongside the progress bar. If it's accurate enough; some apps bluff this, and cause misdirected concern ("my file went through morking and plorking really fast but now the app is hanging 63% of the way through munging"), and we want to avoid that.

But could be cool to have "importing" change to "processing" (or subsets of "processing") in a way that reflects what's actually happening.

**Comment by jeremybmerrill** [comment]
(working on this in feature/multiple, which is of course a child branch of feature/newUI)

**Comment by jeremybmerrill** [comment]
I just merged feature/multiple into feature/newUI. Uploading multiple PDFs now works. I'd love to hear y'all's feedback; there may be bugs and roughness around the edges. (And maybe get a new deploy to try.tabula.technology?)

@floodfish: Do you have any additional feedback on the zero data state -- that is, when a user has no files in their library? Right now what I've got is not great...
![screenshot from 2015-03-16 22 02 02](https://cloud.githubusercontent.com/assets/548250/6680036/3319072c-cc28-11e4-9067-b832e1360fbe.png)

**Comment by floodfish** [comment]
We could just make that whole section disappear. No "Imported PDFs" header, no table headings.

-jason

**Comment by jeremybmerrill** [comment]
Looks a bit spare. Maybe "first-use" copy instead?
![screenshot from 2015-03-20 19 47 55](https://cloud.githubusercontent.com/assets/548250/6762632/85a5ffb2-cf3a-11e4-971b-5cae5d29307e.png)

**Comment by jeremybmerrill** [comment]
Closed; see #296 for continued discussion of hte upload page when there's nothing in the file library.
