### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by KUHFNews** [tabulapdf/tabula#360]
Preview of Extracted Tabular Data
Tabula couldn't finish processing your request. We'd appreciate if you could report this error in our issue tracker. If possible, please include a link to the document that caused the error and the text below:

Tabula API version: 1.0.0
Filename: distinctions.pdf
Internal Server Error (500)
    
      
        Request Method:
        POST
      
      
        Request URL:
      http://127.0.0.1:34555/pdf/f7eb597aa4a9ab18d38240287a5b9d608bcf39fe/data

(ArgumentError) comparison of Float with nil failed

**Comment by jeremybmerrill** [comment]
@KUHFNews is this your document? http://ritter.tea.state.tx.us/perfreport/account/2014/distinctions.pdf

**Comment by jeremybmerrill** [comment]
Thank you for the bug report -- we appreciate it. Assuming that's the right PDF, this issue has been fixed in 6d5c222, which will be included in the next bugfix release of Tabula, which should be released soon.

As I mention in #365, those circles in the report aren't coming through correctly. The rest is, but you'll have to let the data load, then select Stream mode (instead of Lattice mode).

**Comment by KUHFNews** [comment]
Technically it’s the state’s but yes.
