### ISSUE TITLE
Output only showing symbols and no text

### ISSUE THREAD

**Issue by OuchIAteMyself** [tabulapdf/tabula#414]
I am converting a PDF and everything goes fine - the table detection is great, but in the preview and output, I get text like this without any actual proper text for the whole document.:

'44$/%*
+$'&$%,-() 
'/%&(-% -%.() / ,/0 &'0.-$& &'0.-$& 
&,-$ ().$
()" 
$-'1$&2 3 ()" ()" $&-$/% ())'/*
B1, 1 1B, 1B, < 1 <
B , B 1 B 1 < 11 1 < B ,
B B1 B1 < , <1 ,,
B B 1 , B 1 , < , <
B 1 1 < 1 < 1
1 , < 1 <
B B , , B , , < 1 < B ,
B B < B 11

**Comment by jazzido** [comment]
Thanks for your report, @OuchIAteMyself.

It's likely that your PDF has bad glyph-to-character mappings. Try copying and pasting from Acrobat Reader or other PDF viewing app and pasting onto a text editor. Do you also see gibberish instead of the actual text? If so, and unless you're willing to do some serious, low-level PDF debugging, OCR is your only option.

See this Stack Overflow answer for more information: http://stackoverflow.com/questions/12184304/if-pdf-copypaste-gives-garbage-text-what-is-wrong-with-the-pdf-source-code
