### ISSUE TITLE
version conflict? 1.1.0-beta.1 vs. 1.1.0-beta1

### ISSUE THREAD

**Issue by jeremybmerrill** [tabulapdf/tabula#487]
the update notifier bugs me to tell me that `New version! Tabula 1.1.0-beta.1 is available (you have 1.1.0-beta1)`

because the two version strings are different. Is it possible there's a conflict with the version number on GitHub and the version number in Tabula?

Not a big deal since it's the beta and the issue won't occur for the real release, but shruggy.

**Comment by mtigas** [comment]
This is a lot better now as of 4b9f3a0f19d34d05869a2c5d4a114fdd05333f79.

Tabula now checks the `TABULA_VERSION` value (set at build-time) against *either* the whole release name (previous behavior, where we made our GitHub releases titled "1.0.6") or a value in parenthesis inside the release name ("1.1.0 Release (1.1.0.16092117)")).

This essentially makes `TABULA_VERSION` (and the executable version) more reliable, since it's always an *extremely* specific, fully-qualified build ID. And it allows us to be more descriptive in the release title and etc.

(Going forward, for new beta releases, we'd build with `TABULA_VERSION` being some full version/build ID like  `TABULA_VERSION=1.1.1.16092201`, post a GitHub release titled "1.1.1 Beta 1 (1.1.1.16092201)" or some such, and then we have to make sure that `-pre` is in the `UI_VERSION` variable in [webapp/static/js/tabula.js](https://github.com/tabulapdf/tabula/blob/master/webapp/static/js/tabula.js) so that the update-checker accepts pre-release GitHub releases when looking for updates.)
