### ISSUE TITLE
Example of failure to detect column

### ISSUE THREAD

**Issue by stoneadrian3** [tabulapdf/tabula#494]
[Uganda_baseline.pdf](https://github.com/tabulapdf/tabula/files/231537/Uganda_baseline.pdf)
Thanks for a great tool. See attached document Table 2. Tabula couldn't seem to separate the 'Old and 'Total' columns even though there is more or less equal whitespace between them as compared to other columns. Rest of table was fine and Excel 'text to columns' quickly separated the offending columns but would of course be nice to be perfect in one step.

**Comment by jeremybmerrill** [comment]
I assume your selection included the "Diesel" and "Petrol" lines? The problem there is that those headers overlap both columns; Tabula's "Stream" extraction method finds areas within your selection where there's no text to find column boundaries. You can exclude the header to get otherwise-perfect extraction.
