### ISSUE TITLE
Stream vs lattice 

### ISSUE THREAD

**Issue by cpiller** [tabulapdf/tabula#507]
When I use Tabula, it seems stuck on stream, even though my data derives from cells bounded by lines. When I click to switch to lattice, it says there is no data. When I go back to the beginning, it reverts to stream. Am I doing something wrong? Thanks.

**Comment by jeremybmerrill** [comment]
Lattice mode will return no data if the lattice method doesn't pick up any data, so this is not a bug.

You should check to make sure that your selection contains all the bounding lines for your cell. Try giving it a little buffer, in case it's accidentally just a little too small.

Otherwise, send us a link to the PDF or attach it (or, if it's sensitive, send it to me) and I'll see if I can give you more specific advice.

**Comment by cpiller** [comment]
Thanks much. I'm creating selections properly. I wonder if the problem is that the exterior cells have no borders, while the interior ones do. Could that be it?

**Comment by jeremybmerrill** [comment]
yep, that's it. Lattice mode won't work in that case, unfortunately.

**Comment by cpiller** [comment]
Ok, many thanks.


*****
Charles Piller
West Coast Editor
ST*A*T

*Reporting from the frontiers of health and medicine*

510.469.7984
Charles.Piller@statnews.com
@cpiller

*@Statnews*  | Statnews.com <http://www.statnews.com/>  |
facebook.com/Statnews <http://www.facebook.com/statnews>

On Tue, May 24, 2016 at 5:04 PM, Jeremy B. Merrill <notifications@github.com

**Comment by jeremybmerrill** [comment]
Cool, sorry I couldn't find a better solution for ya. 

PS: Fan of STAT :)

**Comment by cpiller** [comment]
Thanks Jeremy. Notwithstanding my issue, I'm a fan of  Tabula!


*****
Charles Piller
West Coast Editor
ST*A*T

*Reporting from the frontiers of health and medicine*

510.469.7984
Charles.Piller@statnews.com
@cpiller

*@Statnews*  | Statnews.com <http://www.statnews.com/>  |
facebook.com/Statnews <http://www.facebook.com/statnews>

On Tue, May 24, 2016 at 5:37 PM, Jeremy B. Merrill <notifications@github.com
