### ISSUE TITLE
Problem with columns being merged in output CSV file 

### ISSUE THREAD

**Issue by rjp0i** [tabulapdf/tabula#555]
I've been trying to use Tabula to extract the table data from a 53 page PDF. It does a pretty amazing job, but has trouble distinguishing a few of the columns as separate columns. The table has the same format on each page, but the merged columns in the resulting CSV file differ from page to page. 

I used the Stream method. When I tried the Lattice method, it returned an empty result (I don't have vertical lines). 

Several of the columns have text across the entire column (and these are the columns that appear to be causing the problem), for those, the only indication that there is a new column is in the header line (which is the same on each page).

I'm attaching the PDF below:
[Textbooks.pdf](https://github.com/tabulapdf/tabula/files/499397/Textbooks.pdf)
Thanks for the great tool, and for any help you can offer.

**Comment by jeremybmerrill** [comment]
Hi @rjp0i:

Thank you for the bug report. Unfortunately, this PDF is pretty pathological. Your diagnosis of the problem is essentially correct: the PDF doesn't have vertical ruling lines to separate columns, and the text in some cells is sometimes so long that it nearly overlaps the next cell. It's this overlap that is confusing the stream algorithm and the lack of vertical ruling lines precludes any possibility of using the lattice algorithm.

Unfortunately, I don't have much of a solution for your PDF. The only possibility I can offer is that you could manually specify the locations of the column boundaries via the command-line tool's `--columns` option. https://github.com/tabulapdf/tabula-java/
