### ISSUE TITLE
Long cells in pdf table become extra rows in csv

### ISSUE THREAD

**Issue by plicplic** [tabulapdf/tabula#625]
Hi,
I got the following problem: when text in a cell is longer than the average text, Tabula uses an extra row in the csv to display it. 

Here's an example:

![image](https://cloud.githubusercontent.com/assets/6008355/22724944/17b50010-edca-11e6-82d0-db14546baeaa.png)

And here is the problem I got in the csv:

![image](https://cloud.githubusercontent.com/assets/6008355/22725064/e8383806-edca-11e6-890b-0353f3591f02.png)

Is there a way to avoid this annoying behaviour?

Thanks for your help!

**Comment by jeremybmerrill** [comment]
Hi Alain,

You can try switching to Lattice mode in Tabula on the data preview page. Lattice mode can often combine those lines.

**Comment by plicplic** [comment]
Hi Jeremy,

I tried this already, without result unfortunately.
Now I installed the command line version to check if there are useful options I could try. But my first tests (with and without the -u combined with -r ) were also unsuccessful.

**Comment by jeremybmerrill** [comment]
Then I don't think there's a solution in Tabula. You will have to fix it manually. (The problem is that PDFs do not have a native concept of a table, so Tabula has to attempt to reconstruct it. If there are no ruling lines, then the Lattice mode will not work; Stream mode uses only the position of text to reconstruct the table structure and cannot account for multiline cells. There is a huge variety of ways to represent multiline cells in PDFs and we don't know of a way to programmatically account for all of them.)

**Comment by plicplic** [comment]
I understand the difficulty very well. Thanks for your suggestion anyway. I have now a very good opportunity (and a deadline as well, lol) to improve my fledgeling awk and sed :-)
