### ISSUE TITLE
Tabula omits minuses

### ISSUE THREAD

**Issue by ruimueller** [tabulapdf/tabula#628]
On many tables of different papers Tabula omits minuses when extracting the tables.
 I am just adding some of the papers that have the problem on every table with minuses.
 I have many more papers with the same problem.

Windows 10, newest Tabula version.

Thanks for an amazing application!

[gender.pdf](https://github.com/tabulapdf/tabula/files/774608/gender.pdf)
[peru.pdf](https://github.com/tabulapdf/tabula/files/774604/peru.pdf)

**Comment by jeremybmerrill** [comment]
@ruimueller: It looks like this is just a very weird PDF. The Mac Preview application also doesn't see the the minuses. Instead, it looks like it's the [Unicode ETX character](https://en.wikipedia.org/wiki/End-of-Text_character), or at least that's what vim and Sublime are telling me.

It is not unheard of for PDFs to make weird modifications to their font tables so that a character that "really" is one thing shows up as another. Unfortunately I don't have a great solution to suggest for you.
