### ISSUE TITLE
bug with alternate extraction method

### ISSUE THREAD

**Issue by nahojtorg** [tabulapdf/tabula#633]
Hi, I think I just encountered a bug. When dealing with the attached pdf, the tables didn't look good at first (it breaks at page 4), so I switched to Lattice mode to see if it gets better. It didn't so I switched back to stream, and the previous error(broken tables) is gone. I tried to reproduce the bug and it does. Running the latest version of Tabula. Thanks for a great application, love it!
 [
[brisk-Cross-Reference-finns nytt.pdf](https://github.com/tabulapdf/tabula/files/789826/brisk-Cross-Reference-finns.nytt.pdf)
](url)

**Comment by jeremybmerrill** [comment]
Thank you for the report of this problem. Tabula attempts to "guess" the right extraction mode per page. So by switching to Lattice, then to Stream, you've forced Tabula to use Stream for all pages. Probably page 4 was erroneously "guessed" to be a table with ruling lines.

So while the "guessing" algorithm is wrong, this is otherwise expected behavior.
