### ISSUE TITLE
Extract area config

### ISSUE THREAD

**Issue by dgn2** [tabulapdf/tabula#640]
Hello,
I have been using tabula to parse financial statements and it is very effective when I manually highlight the area. When I try using the command line, I am having a hard time setting the area. Is there any way to export the manually highlighted areas as a configuration file or something similar? That would be a very helpful feature.

I am a Windows user and I do not know of a tool that can give me the appropriate page coordinates similar to the area I select using the manual Tabula selector tool.

Thanks & Regards,
Derek

**Comment by jeremybmerrill** [comment]
On Tabula's Preview screen, there's a Script download option. That'll
generate a shell script with your selection area included. Might take a
little poking to make it a Windows batch script, but it should be doable.

Jeremy B. Merrill
Sent from my mobile device

On Mar 2, 2017 8:02 PM, "Derek G Nokes" <notifications@github.com> wrote:

Hello,
I have been using tabula to parse financial statements and it is very
effective when I manually highlight the area. When I try using the command
line, I am having a hard time setting the area. Is there any way to export
the manually highlighted areas as a configuration file or something
similar? That would be a very helpful feature.

I am a Windows user and I do not know of a tool that can give me the
appropriate page coordinates similar to the area I select using the manual
Tabula selector tool.

Thanks & Regards,
Derek

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tabulapdf/tabula/issues/640>, or mute the thread

**Comment by dn11** [comment]
That is amazing. Thank you. I cannot believe how quickly you responded.
Thank you!
