### ISSUE TITLE
removing spaces, wonking encoding

### ISSUE THREAD

**Issue by ThePromenader** [tabulapdf/tabula#694]
First off, thanks for all your work on this: it's a much-needed tool.

Everything works fine until export: the result (in French) has spaces lopped out in many places (makingallthewordsjoinintoone) and some of the other spaces, especially at a cell's 'beginning of text', are transformed into 'e's.

Here is the file I attempted to extract.

Thanks, best,

Josef.

[C_REG2A6_01-V03.pdf](https://github.com/tabulapdf/tabula/files/1088392/C_REG2A6_01-V03.pdf)

**Comment by jazzido** [comment]
Thanks for your message, @ThePromenader.

PDF does not encode the notion of a _word_: it just contains information about characters and their positions on the page. Because of that, Tabula (and every other tool that extracts text from PDFs) needs to reconstruct words using those coordinates. 

Text-dense documents (such as yours) sometimes confuse the text extractor.
