### ISSUE TITLE
Morning Consult polls import as gibberish

### ISSUE THREAD

**Issue by aaronwe** [tabulapdf/tabula#713]
I suspect this is intentional obfuscation, but [PDFs from Morning Consult](https://morningconsult.com/wp-content/uploads/2017/08/170803_crosstabs_Politico_v1_TB-1.pdf) import as complete gibberish. Tabula appears to be correctly identifying the tables, but the text is entirely meaningless.

Result CSV (zipped) attached.
[tabula-170803_crosstabs_Politico_v1_TB-1.csv.zip](https://github.com/tabulapdf/tabula/files/1225798/tabula-170803_crosstabs_Politico_v1_TB-1.csv.zip)

**Comment by jazzido** [comment]
Thanks for your report, @aaronw.

It's likely that your PDF has bad glyph-to-character mappings. This might be intentional, but it's usually not. Try copying from Acrobat Reader or other PDF viewing app and pasting onto a text editor. Do you also see gibberish instead of the actual text? If so, and unless you're willing to do some serious, low-level PDF debugging, OCR is your only option.

See this Stack Overflow answer for more information: http://stackoverflow.com/questions/12184304/if-pdf-copypaste-gives-garbage-text-what-is-wrong-with-the-pdf-source-code
