### ISSUE TITLE
No data from tables

### ISSUE THREAD

**Issue by brrrooke** [tabulapdf/tabula#755]
I wasn't able to extract any of the tables in the attached PDF using your tool.
[2003_Shenoy_Thermomechanical Fatigue of Directionally Solidified Ni-Based Superalloy.pdf](https://github.com/tabulapdf/tabula/files/1427264/2003_Shenoy_Thermomechanical.Fatigue.of.Directionally.Solidified.Ni-Based.Superalloy.pdf)

That is, no data showed in the preview or the .csv export.

**Comment by spamjim** [comment]
This is because your tabular data is a scan (graphic image) and not live text. See the instructions for more info.

**Comment by thesilentpsycho** [comment]
It is unable to extract any data for the below pdf as well:-
http://www.bseindia.com/bseplus/AnnualReport/500570/5005700317.pdf

The pdf clearly has lots of tables. I am able to select data from the tables and paste in excel manually. Please help. Are there any options that I must provide while reading using read_pdf method.

Following is screenshot of the same:
![image](https://user-images.githubusercontent.com/13063226/32690278-5b9c5f6a-c71a-11e7-8950-5f5856d58114.png)

**Comment by jeremybmerrill** [comment]
Hi @thesilentpsycho:

1.) It looks like you're using [tabula-py](github.com/chezou/tabula-py), which is a community-supported Python binding for [tabula-java](github.com/tabulapdf/tabula-java). So the Tabula-py forum is the correct place to ask about `read_pdf()` options. This is the support forum for the Tabula GUI web app.
2.) But, yes, you will need to provide additional options to tell Tabula the page number and coordinates of the tables you want to extract -- because the data tables in that report (at least, my guess for the ones you want to extract) don't have ruling lines and cannot be automatically detected.
