### ISSUE TITLE
Thousands Comma Issue

### ISSUE THREAD

**Issue by Mkline4** [tabulapdf/tabula#770]
The values in my tables over 1000 have a comma every three digits (i.e. "3,000").  When I extract the data for Excel it is deliminated using commas.  When I open the exported file, I end up with extra columns that have my values split between cells (i.e. a column with "3" and another with "000").

Is there any way to change the deliminator?  Excel will allow the user to select a different symbol when importing. 

Thank you for your help!

**Comment by jeremybmerrill** [comment]
Hi @Mkline4 :

Two options:

I suspect that the CSV file you have has each field (or at least each field with commas) set off by quotation marks. My guess is that your Excel version is ignoring these quotation marks, which is how Excel should be able to make sense of the three cells in a line like `"Dallas, TX", 75001, "$1,234"`

Alternatively, you can select the TSV download option in Tabula, in the Preview screen. This is a Tab-Separated Values document -- exactly the same as a CSV, but with tabs instead of commas. Excel should be able to open it properly, but, since there are not tabs in your document, there's no confusion between the delimiter and literal commas.

Hope this helps.

**Comment by Mkline4** [comment]
@jeremybmerrill  Thanks!  Works perfectly.

**Comment by jeremybmerrill** [comment]
Glad to hear!

Jeremy B. Merrill
