### ISSUE TITLE
Tabula on mac returns junk from the attached pdf

### ISSUE THREAD

**Issue by GeraldCNelson** [tabulapdf/tabula#793]
This pdf looks to have a very simple table structure. But attempts to convert to csv have just resulted in junk. The autodetect feature finds the table just fine but attempts to convert to csv don't work.
[FAO_ANNEX_I1_fish edible portions.pdf](https://github.com/tabulapdf/tabula/files/1728727/FAO_ANNEX_I1_fish.edible.portions.pdf)

**Comment by jazzido** [comment]
Thanks for your report.

It's likely that your PDF has bad glyph-to-character mappings. Try copying from Acrobat Reader or other PDF viewing app and pasting onto a text editor. Do you also see gibberish instead of the actual text? If so, and unless you're willing to do some serious, low-level PDF debugging, OCR is your only option.

See this Stack Overflow answer for more information: http://stackoverflow.com/questions/12184304/if-pdf-copypaste-gives-garbage-text-what-is-wrong-with-the-pdf-source-code
