### ISSUE TITLE
Export Data displays blank bars in Stream

### ISSUE THREAD

**Issue by StephenSartin-TGS** [tabulapdf/tabula#795]
I am having issues getting data to extract from [this](https://github.com/tabulapdf/tabula/files/1737147/2016_4.pdf) pdf. Uploaded and extracted. ![tabula pdf selection](https://user-images.githubusercontent.com/26577659/36384073-aa3b3c04-1553-11e8-992a-ee32061331d5.png)
Clicked repeat selection and then export. The result was 4 blank lines in Stream.

This works fine with other similar pdfs.
[2017_01.pdf](https://github.com/tabulapdf/tabula/files/1737219/2017_01.pdf)

Using Windows 10 on Firefox Dev Ed 59.0b9 and tabula 1.1.1

**Comment by StephenSartin-TGS** [comment]
It seems to be able to pick up "Gas," from the header of the last pdf when I expand the selection to the entire pdf.
![tabula pdf selection stream](https://user-images.githubusercontent.com/26577659/36385066-170e3a54-1557-11e8-98b9-e7b30c8ac601.png)

**Comment by jazzido** [comment]
Hi @StephenSartin-TGS,

Thanks for reporting this issue. This is likely a limitation of the version of PDFBox (the PDF parsing library used by the current version of Tabula). I just tested your PDF with the _development_ version, that uses a newer PDFBox, and it seems to work as expected:

![image](https://user-images.githubusercontent.com/27584/36388416-8e90ff62-157a-11e8-904a-5d95382d643b.png)

This version will be released in the coming days. Otherwise, if you're comfortable with the command line, you can try [tabula-java](http://github.com/tabulapdf/tabula-java)
