### ISSUE TITLE
First row with vertical text not properly recognized

### ISSUE THREAD

**Issue by setaur** [tabulapdf/tabula#821]
I'm trying to process tables from
http://www.eko.sulejow.pl/asp/pliki/Harmonogramy_wywozu_odpadow/od_2_marca_2018r_harmonogram.pdf

Here is image of a table from that pdf (page 1):
![pdftable](https://user-images.githubusercontent.com/8095789/37493861-bec25ff2-28a6-11e8-9184-20317d8b5481.png)

And here is a processing result using lattice extraction method and autodetection of tables:
![pdftable2](https://user-images.githubusercontent.com/8095789/37493900-e27cc126-28a6-11e8-9402-97322aa0b131.png)

As you can see first row with vertical strings is mashed inside a middle of a table.
Stream extraction method produce even worse output.

I'm running newest tabula binary on a Linux (Debian Stretch) computer. System language: Polish.

**Comment by jazzido** [comment]
Hi @setaur,

Thanks for reporting this issue. That's the expected behaviour; Tabula does not support vertical text (yet). I'd recommend that you leave the row with vertical text out of the selection, and add those cells manually after extraction.

![image](https://user-images.githubusercontent.com/27584/37525293-2f1783ea-290b-11e8-992f-39baece5126a.png)
