### ISSUE TITLE
Error in identifying columns when table structure has few boundaries missing.

### ISSUE THREAD

**Issue by idhant96** [tabulapdf/tabula#919]
![screenshot from 2018-09-19 10-24-09](https://user-images.githubusercontent.com/11132722/45731661-4e037b00-bbf6-11e8-8dcf-70a7ad3b9275.png)

The result combines two columns VIA PORT and CHARGES column into one. By turning off the guess parameter False, the result comes haphazard and does not serve any purpose.

**Comment by jeremybmerrill** [comment]
Yes, this is definitely a pathological table/PDF. As you've correctly noticed, the missing boundaries are the main source of the problem: Tabula's "lattice" mode won't work because they're broken. You can try "stream" mode (aka "no-spreadsheet" in the command line app), but it won't be perfect on the cells with multiple lines of next. You'll also want to exclude the headers from the selection.

Unfortunately, that's all I can suggest. While ideally Tabula could support extracting data from this PDF, neither of our extraction algorithms can at the moment. Those algorithms are working correctly, they just can't handle this PDF. So I've got to close this as wontfix.

Perhaps if someone seeks to add another extraction algorithm, they could use this as a test case.
